### ISSUE TITLE
Setup SwiftLint

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#10]
Linting is a great way of ensuring that a repository's code is neat. Setting up SwiftLint consists of two steps:

- [x] Create the SwiftLint configuration file and decide which rules to use
- [ ] Create a GitHub action to automatically run SwiftLint

**Comment by ajstrand** [comment]
Do you have an idea of which rules you'd like to support?

From looking at swift lint it seems like there are quite a lot.

**Comment by stackotter** [comment]
I've setup a basic configuration now (on the `dev` branch). Many of the good SwiftLint rules are just enabled by default, so it's pretty close to a default configuration, just with a few changes (such as ignoring files generated by `gyb`). I've set up a simple GitHub Action for it too 👍
