### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#11]
Theoretically, SwiftCrossUI should work on Windows, but I haven't managed to install Gtk on Windows in a way that Swift can use yet. If you use Swift on Windows, you'll probably have more luck than I did! Feel free to try and get it running.

If you do manage to get it working, please let us now how, so that we can setup a GitHub action for Windows builds. And if an code changes are required to get it running, just make a PR.

**Comment by stevapple** [comment]
We had once got there since Gtk+ 3.24 was able to be built. It turned out that Gtk+ 4, however, cannot be built with static linking on Windows (at least with Vcpkg, seemingly the only package manager we can use).

Keep and eye on https://github.com/microsoft/vcpkg/issues/31830. We're almost there.

**Comment by Amzd** [comment]
We are very interested in getting this working on Windows! If you get this working or have any questions about SwiftCrossUI side or if we need to change anything to support Windows please comment on this issue or for quick contact we frequent discord here: https://discord.gg/zd7Trztdnk

**Comment by stackotter** [comment]
Im pretty sure @stevapple got this working so I’m closing it.
