### ISSUE TITLE
Implement more view types

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#2]
Currently only `HStack`, `VStack`, `Button` and `Text` are supported. The following view types would also be useful to have:

- [x] `TextField`
- [x] `Slider`
- [x] `ForEach`
- [x] `Image`

If you think of any more, reply below.

For reference on how to implement a container view, see the `VStack` implementation. For how to implement a non-container view, see the `Button` implementation.

**Comment by NinjaCheetah** [comment]
Not entirely sure if SwiftGtk supports it but a `Picker` would be nice to have.

**Comment by stackotter** [comment]
I've implemented these 4 view types now (as well as implementing some views required for control flow). And I'll implement a `Picker` now. Further view types can be given their own issues as views are easier to implement now 👍

**Comment by stackotter** [comment]
Actually, Picker might take a little while to implement so I'll do that later once I've made some more API improvements.
