### ISSUE TITLE
Create Picker view

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#23]
SwiftUI has a `Picker` view that allows a user to select an option from a list, which is implemented by the `Menu` widget in Gtk. It'd be nice for SwiftCrossUI to have a dropdown menu type too (called `Picker` for consistency with SwiftUI).

**Comment by Amzd** [comment]
It is now called DropDown in gtk4 https://docs.gtk.org/gtk4/class.DropDown.html

We should decide how truthful we want to stay to the SwiftUI api. In DropDown there is no widget children, it just needs an array of strings, which I am not sure if we can create from a ViewContent currently? 

```swift
// SwiftUI
Picker(...) {
  Text("Option 1")
  Text("Option 1")
  Text("Option 1")
}
// an easier solution if we can't get strings from ViewContent3<Text, Text, Text>:
Picker(..., options: [String])

**Comment by stackotter** [comment]
If we want to stick to the SwiftUI API, we can technically create a special result builder that just takes `Text` instead of `View` and has the output type `[String]` (should be relatively easy), then we'd be able to support if/else etc still

**Comment by Amzd** [comment]
That seems like a great solution.

**Comment by stackotter** [comment]
It turns out that DropDown does support widgets as children. The DropDown API is pretty terrible lol.

To set the option labels to arbitrary widgets we have to make a factory to produce the widgets for the options (the strings initialiser just creates a listmodel from the strings and then uses a default factory which makes a widget with a check-mark if selected, and a label with the option's name).

Annoyingly, DropDown doesn't have any signals related to the value changing (wtf gtk). To get notified whenever the selection changes, we'll need to do something dodgy with `g_object_bind_property_full` probably (and the transformfunc can effectively be the signal handler).

**Comment by stackotter** [comment]
I’ve implemented a picker view now, unfortunately it doesn’t work on macOS, but that’s a Gtk issue, even in the official Gtk demo the dropdowns don’t work.

Currently the options are just displayed as strings, there’s no way to customise the presentation of the options.
