### ISSUE TITLE
Implement a layout system

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#4]
Currently, the layout of views is at the mercy of Gtk, which is not too great. Gtk supports styling through CSS, so the layout system would most likely just consist of generating css for each component according to certain layout rules. But there may be a better approach that I haven't thought of.

The [SwiftGtk package](https://github.com/stackotter/SwiftGtk) currently doesn't support CSS styling which means that [the styling feature request for SwiftGtk](https://github.com/stackotter/SwiftGtk/issues/1) would have to be completed first.

**Comment by Amzd** [comment]
We now have some limited layout:

- Alignment through `Spacer`:
```swift
/// horizontal alignment
HStack {
  Spacer()
  Content()
}
```
```swift
/// vertical alignment
VStack {
  Spacer()
  Content()
}
```
- Forced minimum size using `.frame(minWidth:maxWidth:)`
```swift
Content().frame(minWidth: 200)
```
- Padding
```swift
Content().padding(10)
```

Maybe we should define which layout features we would like next

**Comment by stackotter** [comment]
That's almost all of the main ones done, I can't really think of any off the top of my head other than navigation layouts, but that's also pretty good now. I feel like it's almost time to start trying to build some more complicated apps and just see what's missing in practice

**Comment by stackotter** [comment]
The new layout system fixes the existing implementations of layout primitives and expands them to be fully featured. For example, the frame modifier now supports setting minimum, ideal, and maximum values for both width and height. And spacers now expand correctly no matter the backend cause they're implemented completely within SwiftCrossUI itself.

We've also had the navigation layouts that I mentioned for a while.

I believe that the new layout system is at a point now where any additional layout feature requests can get their own issues.
