### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Adamekka** [stackotter/swift-cross-ui#45]
```sh
$ swift run CounterExample
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```
my OS is MacOS
I have installed `xcode-select --install` and gtk4 via `brew install gtk4`

**Comment by stackotter** [comment]
What's the output of `xcode-select --print-path`? This looks like a configuration issue to me.

One option (which may not be necessary if you can get the command line tools working) would be to install Xcode if you have the space/time available to do that.

**Comment by Adamekka** [comment]
```sh
$ xcode-select --print-path
/Library/Developer/CommandLineTools
```
I have Xcode installed
I have everything up to date - macOS, App Store apps, and Brew apps
I have almost no configuration on this system, this Mac is like a week old since the factory reset

**Comment by stackotter** [comment]
You need to run `sudo xcode-select --switch /Applications/Xcode.app` so that it points to your Xcode installation (I assume that’s the path to you Xcode, but if it’s not just replace it in the command)

**Comment by Adamekka** [comment]
Thanks a lot, it worked!

**Comment by Adamekka** [comment]
I have left a star for your help

**Comment by stackotter** [comment]
Awesome 👍 don’t hesitate to let me know if you face any other issues or find features you need/want added
