### ISSUE TITLE
Warnings on Ubuntu 22.04

### ISSUE THREAD

**Issue by lhoward** [stackotter/swift-cross-ui#48]
Not sure if these are spurious, but I'm seeing the following warnings running the test programs:

```
(SplitExample:479232): GLib-GIO-CRITICAL **: 10:49:43.780: g_dbus_connection_emit_signal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed

(SplitExample:479232): GLib-GIO-CRITICAL **: 10:49:43.780: g_dbus_connection_emit_signal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed

(SplitExample:479232): GLib-GIO-CRITICAL **: 10:49:43.809: g_dbus_connection_register_object: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed

(SplitExample:479232): GLib-GIO-CRITICAL **: 10:49:43.809: g_dbus_connection_register_object: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
```

**Comment by stackotter** [comment]
Is this with the latest commit of the `main` branch? I have a 22.04 testing machine and haven't run into those warnings (although I seem to remember fixing similar warnings in a past commit)

**Comment by lhoward** [comment]
Yup, I'm on `main`.

**Comment by stackotter** [comment]
What Swift compiler version are you using? Maybe it could be related to that? (seems unlikely) I tried with Swift 5.7.2 (I forgot that I had switched to that to investigate a bug with something else a while ago)

**Comment by lhoward** [comment]
I’m on 5.9 snapshot as I wanted to use the new Foundation.

**Comment by stackotter** [comment]
Ok cool, I’ll test it out tonight with 5.9 and see if I get the warnings

**Comment by stackotter** [comment]
Just tested with Swift 5.9 and I still don't get those warnings, I wonder what difference between our systems is causing the issue.

My gtk4 version is 4.6.5 (a bit outdated) what version is yours?

**Comment by lhoward** [comment]
Maybe it's my weird window manager (NsCDE). I'll close for now :)

**Comment by stackotter** [comment]
Ok sounds good. When I get back I’ll have a quick look through the code to see if there’s anything that might be causing it
