### ISSUE TITLE
Support multiple windows

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#5]
SwiftUI approaches this by having the body of `App` be of type `some Scene` where a scene can define windows using a result builder.

The way I plan on approaching this is making `App.body` be of type `some AppContent` and having a `Window` struct that `AppContentBuilder` accepts. Then `_App` can setup the windows accordingly in `run`.

**Comment by Amzd** [comment]
Note: Don't forget to use the correct window in `Widget.cssProvider` when we implement this

**Comment by stackotter** [comment]
SwiftCrossUI has supported multiple windows for a while now, I just forgot to close this issue when I implemented multi-window support.
