### ISSUE TITLE
Update the Examples documentation articles to include newest examples

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#64]
Since creating [the Examples article](https://stackotter.github.io/swift-cross-ui/documentation/swiftcrossui/examples) for the documentation, two new examples have been introduced: `SplitExample` (to showcase multi-level side-bar navigation), and `StressTestExample` (to keep an eye on view update performance). These should be added to the article along with short descriptions (just like all the rest of the examples).

**Comment by Ethaaan11** [comment]
@stackotter could i be assigned to this task please?

**Comment by stackotter** [comment]
Yep sure!

**Comment by stackotter** [comment]
@Ethaaan11 I've unassigned you now in order to not have the issue locked up, but if you still want to complete it I'm of course happy to assign you again

**Comment by NinjaCheetah** [comment]
Just since it's been a bit and this should be a pretty quick task, I'm going to go ahead and add them.

**Comment by stackotter** [comment]
Sounds good 👌 The only reason I opened this instead of doing it was to try and entice new contributors during Hacktoberfest 😅 Almost worked

**Comment by NinjaCheetah** [comment]
Should also be resolved by #70 (and whoa did not mean to take an entire month to actually get that done lol).
