### ISSUE TITLE
Building basic app with library fails.

### ISSUE THREAD

**Issue by thecodecommander2580** [stackotter/swift-cross-ui#72]
When building using the provided example code in the README, I get the error: "error: no such module 'GtkBackend'".
Building the examples provided in the repo works just fine.
I am building under WSL 2 Ubuntu.

**Comment by stackotter** [comment]
Have you installed Gtk 4, added GtkBackend as a dependency in your Package.swift, and imported GtkBackend? Those are the first things that come to mind from that error

**Comment by thecodecommander2580** [comment]
The GtkBackend dependency was the problem. Thanks!
Also, the example code from README.md doesn't compile anymore. You should probably update it to match the code in the Examples folder.

**Comment by stackotter** [comment]
Awesome!

Ah whoops, it seems I typoed while updating the example a few days ago, `some ViewContent` should be `some Scene`. Thanks for letting me know!
