### ISSUE TITLE
Update the Discord link in README

### ISSUE THREAD

**Issue by Advait1306** [stackotter/swift-cross-ui#74]
The current link in the README.md file is expired. Discord has way of creating non expiring invite URLs, please use that and change the link.

https://support.discord.com/hc/en-us/articles/208866998-Invites-101

**Comment by stackotter** [comment]
Both links seem to be working for me (I know how to make non-expiring invite links, and both of the links in the readme aren’t expired according to Discord). I’ll double check when I get home to my laptop. Maybe there’s a third invite I didn’t see on my phone.

Does this work for you? https://discord.gg/fw2trT48ny

**Comment by Advait1306** [comment]
Okay, there was an issue in my discord itself, it wasn't logged in. But somehow this was the error screen I was seeing. Nonetheless I was able to join with the link in the README.

<img width="933" alt="Screenshot 2023-12-22 at 8 37 54 AM" src="https://github.com/stackotter/swift-cross-ui/assets/42912342/a286a4d4-5630-470a-81ab-36bbef900a55">
