### ISSUE TITLE
Get rid of `identifier` requirement of `App` protocol

### ISSUE THREAD

**Issue by stackotter** [stackotter/swift-cross-ui#89]
The `identifier` property is only used by Gtk so I reckon `GtkBackend` should just use a default value and provide some way to configure it. Alternatively, we could just provide a default implementation of the `identifier` property which has some default identifier such as `com.example.Example` (not sure what a good default would be).

**Comment by warmachinesocial** [comment]
Did you mean this under GtkBackend.swift

```public final class GtkBackend: AppBackend {
    public typealias Window = Gtk.Window
    public typealias Widget = Gtk.Widget

    var gtkApp: Application

    /// A window to be returned on the next call to ``GtkBackend/createWindow``.
    /// This is necessary because Gtk creates a root window no matter what, and
    /// this needs to be returned on the first call to `createWindow`.
    var precreatedWindow: Window?

    public init(appIdentifier: String) {
        gtkApp = Application(applicationId: appIdentifier)
    }

**Comment by warmachinesocial** [comment]
I was like just have the project name as the unique identifier rather than "com.example.projectName" -> "projectName"

**Comment by stackotter** [comment]
Yeah, that initialiser is currently the only piece of code that actually uses the appIdentifier for anything, the other backends just ignore it, so it should be a gtk specific setting instead of a setting provided to all backends.

**Comment by stackotter** [comment]
Completed this on the `layout_system` branch a little while ago.
